include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - archive/**
    - web-dist/**
    - lib/services/browser_file_picker_web.dart
    - lib/services/create_media_library_web.dart
    - web/**

linter:
  rules:
    avoid_print: true
